version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/{{cookiecutter.project_name}}"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: pre-commit
    directories:
      - "/"
      - "/{{cookiecutter.project_name}}"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      pre-commit:
        patterns:
          - "*"
