# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
    os: ubuntu-24.04
    tools:
        python: "3.13"
    commands:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
        - uv venv
    install:
        - uv pip install .[doc]
    build:
         html:
            - uv run sphinx-build -T -W -b html docs $READTHEDOCS_OUTPUT/html

# uncomment this to include git submodules such as external tutorial repositories
#submodules:
#    include: all
