# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
    os: ubuntu-24.04
    tools:
        python: "3.12"
    commands:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
        - uv venv
        - uv pip install .[doc]
        - .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
sphinx:
    configuration: docs/conf.py
    # disable this for more lenient docs builds
    fail_on_warning: true

# uncomment this to include git submodules such as external tutorial repositories
#submodules:
#    include: all
