name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.10"]
        os: [ubuntu-latest]
        pre-release: [false]
        # add one additional job to test against pre-releases on the latest Python version
        include:
          - os: ubuntu-latest
          - python: "3.10"
          - pre-release: true

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip wheel
      - name: Install dependencies
        if: ${{ !matrix.pre-release }}
        run: |
          pip install ".[dev,test]"
      - name: Install pre-release versions of dependencies
        if: ${{ matrix.pre-release }}
        run: |
          pip install --pre ".[dev,test]"
      - name: Test
        env:
          MPLBACKEND: agg
          PLATFORM: ${{ matrix.os }}
          DISPLAY: :42
        run: |
          pytest -v --cov --color=yes
      - name: Upload coverage
        uses: codecov/codecov-action@v3
