name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.14"]
        os: [ubuntu-latest]
        # one that matches "project-name".lower().replace('-', '_'), one that doesn’t:
        package-name: [project_name, package_alt]
    env:
      PROJECT_ROOT: project-name

    steps:
      # Setup
      - uses: actions/checkout@v5
      - name: Set git identity
        run: |
          git config --global user.name "scverse-bot"
          git config --global user.email "108668866+scverse-bot@users.noreply.github.com"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}
          cache-dependency-glob: "{{cookiecutter.project_name}}/pyproject.toml"
      - name: Install Ubuntu system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install pandoc
      - name: Install build & check dependencies
        run: |
          uv tool install pre-commit --with=pre-commit-uv
          uv tool install cruft --with=pre-commit-uv
          uv tool install hatch
      # Build
      - name: Build from template
        run: cruft create  . --no-input --extra-context='{"package_name":"${{ matrix.package-name }}"}'
      # Check
      - name: Run pre-commit
        run: |
          cd "$PROJECT_ROOT"
          git add .
          pre-commit run --verbose --color=always --show-diff-on-failure --all-files
      - name: Install the package and check if it can be imported
        run: |
          cd "$PROJECT_ROOT"
          uv run python -c "import ${{ matrix.package-name }}"
      # Docs
      - name: Build the documentation
        if: matrix.python == '3.14'
        run: |
          cd "$PROJECT_ROOT"
          hatch run docs:build

  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set git identity
        run: |
          git config --global user.name "scverse-bot"
          git config --global user.email "108668866+scverse-bot@users.noreply.github.com"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: scripts/pyproject.toml
      - name: set git default branch
        run: git config --global init.defaultBranch main
      - name: Run tests
        env:
          SCVERSE_BOT_READONLY_GITHUB_TOKEN: ${{ secrets.SCVERSE_BOT_READONLY_GITHUB_TOKEN }}
        working-directory: ./scripts
        run: uvx hatch test
